### PR TITLE
 select one word mode just like Quick Translator

### PR DESCRIPTION
**Pull request by uomar8**
works greate 👍👍👍

 i just rename the brunsh and it remove the pull my bad sorry

### CODE REVIEW

**Comment by firemaples** [comment]
@uomar8 Finished, please check if it fits your imagination. 😀

**Comment by uomar8** [comment]
> @uomar8 Finished, please check if it fits your imagination. 😀

the code is work great as always

I have a problem with translate one word
Translate one word should include all other possible translation if it's give only one translation it won't be that helpful 

Screenshot_20230110_181452

And it's shouldn't remove the translation so you could choose what translation fit the most for that word

**Comment by firemaples** [comment]
The translation services including Microsoft and Google only provide one translation. 😅

**Comment by uomar8** [comment]
> The translation services including Microsoft and Google only provide one translation. 😅

That's why it's good to use WebView for that 

cfyfcyd (20230110085723)_edit_94339200676228

It will be the same as Quick Translator but the only difference that it will edit HTML to remove unwanted space

It will be like click on the word and get more information about the word from

Google translate website (to get more translations)
Google images ( to see pictures of the word to understand it more)
It would be so helpful

**Comment by firemaples** [comment]
Okay, get it, your idea is great!
I will think about how to present the UI.

And about modifying the HTML, I'm not sure if it's legal or not, I'll double-check the feasible way.

**Comment by uomar8** [comment]
> Okay, get it, your idea is great! I will think about how to present the UI.
> 
> And about modifying the HTML, I'm not sure if it's legal or not, I'll double-check the feasible way.

You're right, I hope it's legal

if not we could use the idea of Ad Block, but instead remove unwanted elements without modifying the HTML and keep the white spaces and changed

**Comment by uomar8** [comment]
I think it looks so great now amazing work as always

**Comment by firemaples** [comment]
Let me adjust the UI.
And I can try to add the image search on this page.

**Comment by firemaples** [comment]
@uomar8  I will release the v3.1.8 version with this feature tomorrow if there are no other concerns. 🎉

**Comment by uomar8** [comment]
> @uomar8 I will release the v3.1.8 version with this feature tomorrow if there are no other concerns. 🎉

there's a crush happen when i switch between tabs in webview ( it doesn't close the app only the webview)

this is the log before it crush

2023-01-16 21:17:15.362 24791-24791 TextInfoSearchView      tw.firemaples.onscreenocr_debug      D  [main] Load web: https://www.google.com/search?q=DEGRADING
2023-01-16 21:17:16.036 24791-24791 chromium                tw.firemaples.onscreenocr_debug      I  [INFO:CONSOLE(41)] "Ignored attempt to prefetch https://www.merriam-webster.com/dictionary/degrading due to unacceptable referrer policy (origin).", source: https://www.google.com/search?q=DEGRADING (41)
2023-01-16 21:17:16.036 24791-24791 chromium                tw.firemaples.onscreenocr_debug      I  [INFO:CONSOLE(41)] "Ignored attempt to prefetch https://www.merriam-webster.com/dictionary/degrading due to unacceptable referrer policy (origin).", source: https://www.google.com/search?q=DEGRADING (41)
2023-01-16 21:17:16.036 24791-24791 chromium                tw.firemaples.onscreenocr_debug      I  [INFO:CONSOLE(41)] "Ignored attempt to prefetch https://dictionary.cambridge.org/dictionary/english/degrading due to unacceptable referrer policy (origin).", source: https://www.google.com/search?q=DEGRADING (41)
2023-01-16 21:17:16.150 24791-26842 <no-tag>                tw.firemaples.onscreenocr_debug      D  PlayerBase::PlayerBase()
2023-01-16 21:17:16.153 24791-26842 <no-tag>                tw.firemaples.onscreenocr_debug      D  TrackPlayerBase::TrackPlayerBase()
2023-01-16 21:17:16.153 24791-26842 libOpenSLES             tw.firemaples.onscreenocr_debug      I  Emulating old channel mask behavior (ignoring positional mask 0x1, using default mask 0x1 based on channel count of 1)
2023-01-16 21:17:16.550 24791-24791 ViewRootImpl@58f7311[]  tw.firemaples.onscreenocr_debug      D  ViewPostIme pointer 0
2023-01-16 21:17:16.657 24791-24791 ViewRootImpl@58f7311[]  tw.firemaples.onscreenocr_debug      D  ViewPostIme pointer 1
2023-01-16 21:17:16.677 24791-25160 OpenGLRenderer          tw.firemaples.onscreenocr_debug      D  eglDestroySurface = 0x75e223a980, 0x75bfedf000
2023-01-16 21:17:16.805 24791-24791 ViewRootImpl@58f7311[]  tw.firemaples.onscreenocr_debug      D  dispatchDetachedFromWindow
2023-01-16 21:17:16.838 24791-24791 InputTransport          tw.firemaples.onscreenocr_debug      D  Input channel destroyed: fd=94
2023-01-16 21:17:16.873 24791-24791 ViewRootImpl            tw.firemaples.onscreenocr_debug      E  sendUserActionEvent() returned.
2023-01-16 21:17:16.873 24791-24791 InputTransport          tw.firemaples.onscreenocr_debug      D  Input channel destroyed: fd=122
2023-01-16 21:17:17.243 24791-24791 ViewRootImpl@22c7046[]  tw.firemaples.onscreenocr_debug      D  MSG_RESIZED: frame=[0,0][168,84] ci=[0,0][0,0] vi=[0,0][0,0] or=2
2023-01-16 21:17:17.243 24791-24791 ViewRootImpl@3b7dd64[]  tw.firemaples.onscreenocr_debug      D  MSG_RESIZED: frame=[0,0][2048,1536] ci=[0,0][0,0] vi=[0,0][0,0] or=2
2023-01-16 21:17:17.313 24791-24791 ViewRootImpl@3b7dd64[]  tw.firemaples.onscreenocr_debug      D  Relayout returned: old=[0,0][2048,1536] new=[0,0][2048,1536] result=0x21 surface={true 506652225536} changed=false
2023-01-16 21:17:17.315 24791-25160 OpenGLRenderer          tw.firemaples.onscreenocr_debug      D  eglDestroySurface = 0x75cb1d9c00, 0x75f6d37000
2023-01-16 21:17:17.326 24791-25160 OpenGLRenderer          tw.firemaples.onscreenocr_debug      D  eglCreateWindowSurface = 0x75cb1d9c00, 0x75f6d37010
2023-01-16 21:17:17.396 24791-24791 ViewRootImpl@22c7046[]  tw.firemaples.onscreenocr_debug      D  Relayout returned: old=[0,0][168,84] new=[0,0][168,84] result=0x1 surface={true 505899155456} changed=false
2023-01-16 21:17:17.402 24791-26842 <no-tag>                tw.firemaples.onscreenocr_debug      D  PlayerBase::stop() from IPlayer
2023-01-16 21:17:17.402 24791-26842 AudioTrack              tw.firemaples.onscreenocr_debug      D  stop() called with 56464 frames delivered
2023-01-16 21:17:17.413 24791-24791 ViewRootImpl@3b7dd64[]  tw.firemaples.onscreenocr_debug      D  MSG_RESIZED: frame=[0,0][2048,1536] ci=[0,0][0,0] vi=[0,0][0,0] or=2
2023-01-16 21:17:17.535 24791-26842 <no-tag>                tw.firemaples.onscreenocr_debug      D  PlayerBase::stop() from IPlayer
2023-01-16 21:17:17.535 24791-26842 AudioTrack              tw.firemaples.onscreenocr_debug      D  stop() called with 3543 frames delivered
2023-01-16 21:17:17.577 24791-26842 <no-tag>                tw.firemaples.onscreenocr_debug      D  PlayerBase::stop() from IPlayer
2023-01-16 21:17:17.577 24791-26842 AudioTrack              tw.firemaples.onscreenocr_debug      D  stop() called with 3543 frames delivered

**Comment by uomar8** [comment]
same thing with the emulter this time i took full logcat

2023-01-16 22:28:41.337  7996-8065  EGL_emulation           tw.firemaples.onscreenocr_debug      D  eglMakeCurrent: 0xe3d875e0: ver 2 0 (tinfo 0xe232e6a0)
2023-01-16 22:28:41.414  7996-8065  EGL_emulation           tw.firemaples.onscreenocr_debug      D  eglMakeCurrent: 0xe3d875e0: ver 2 0 (tinfo 0xe232e6a0)
2023-01-16 22:28:41.468  2097-2196  GnssLocationProvider    system_process                       I  WakeLock acquired by sendMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@b72cc69)
2023-01-16 22:28:41.468  2097-2124  GnssLocationProvider    system_process                       I  WakeLock released by handleMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@b72cc69)
2023-01-16 22:28:41.550  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      E  glUtilsParamSize: unknow param 0x000085b5
2023-01-16 22:28:41.550  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      E  glUtilsParamSize: unknow param 0x000085b5
2023-01-16 22:28:41.551  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 0 (0) 0 0
2023-01-16 22:28:41.556  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 3 (3) 0 0
2023-01-16 22:28:41.562  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 0 (0) 23 0
2023-01-16 22:28:41.585  7996-8065  EGL_emulation           tw.firemaples.onscreenocr_debug      D  eglMakeCurrent: 0xe3d875e0: ver 2 0 (tinfo 0xe232e6a0)
2023-01-16 22:28:41.650  7996-8065  EGL_emulation           tw.firemaples.onscreenocr_debug      D  eglMakeCurrent: 0xe3d875e0: ver 2 0 (tinfo 0xe232e6a0)
2023-01-16 22:28:41.654  7996-7996  TextInfoSearchView      tw.firemaples.onscreenocr_debug      D  [main] Load web: https://www.google.com/search?tbm=isch&q=Photos
2023-01-16 22:28:41.797  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      E  glUtilsParamSize: unknow param 0x000085b5
2023-01-16 22:28:41.797  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      E  glUtilsParamSize: unknow param 0x000085b5
2023-01-16 22:28:41.797  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 0 (0) 0 0
2023-01-16 22:28:41.799  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 3 (3) 0 0
2023-01-16 22:28:41.805  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 0 (0) 23 0
2023-01-16 22:28:41.840  7996-8065  EGL_emulation           tw.firemaples.onscreenocr_debug      D  eglMakeCurrent: 0xe3d875e0: ver 2 0 (tinfo 0xe232e6a0)
2023-01-16 22:28:41.907  7996-8065  EGL_emulation           tw.firemaples.onscreenocr_debug      D  eglMakeCurrent: 0xe3d875e0: ver 2 0 (tinfo 0xe232e6a0)
2023-01-16 22:28:42.007  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      E  glUtilsParamSize: unknow param 0x000085b5
2023-01-16 22:28:42.007  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      E  glUtilsParamSize: unknow param 0x000085b5
2023-01-16 22:28:42.008  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 0 (0) 0 0
2023-01-16 22:28:42.014  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 3 (3) 0 0
2023-01-16 22:28:42.016  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 0 (0) 23 0
2023-01-16 22:28:42.043  7996-8065  EGL_emulation           tw.firemaples.onscreenocr_debug      D  eglMakeCurrent: 0xe3d875e0: ver 2 0 (tinfo 0xe232e6a0)
2023-01-16 22:28:42.091  7996-8065  EGL_emulation           tw.firemaples.onscreenocr_debug      D  eglMakeCurrent: 0xe3d875e0: ver 2 0 (tinfo 0xe232e6a0)
2023-01-16 22:28:42.212  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      E  glUtilsParamSize: unknow param 0x000085b5
2023-01-16 22:28:42.212  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      E  glUtilsParamSize: unknow param 0x000085b5
2023-01-16 22:28:42.213  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 0 (0) 0 0
2023-01-16 22:28:42.215  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 3 (3) 0 0
2023-01-16 22:28:42.220  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 0 (0) 23 0
2023-01-16 22:28:42.246  7996-8065  EGL_emulation           tw.firemaples.onscreenocr_debug      D  eglMakeCurrent: 0xe3d875e0: ver 2 0 (tinfo 0xe232e6a0)
2023-01-16 22:28:42.292  7996-8065  EGL_emulation           tw.firemaples.onscreenocr_debug      D  eglMakeCurrent: 0xe3d875e0: ver 2 0 (tinfo 0xe232e6a0)
2023-01-16 22:28:42.427  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      E  glUtilsParamSize: unknow param 0x000085b5
2023-01-16 22:28:42.427  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      E  glUtilsParamSize: unknow param 0x000085b5
2023-01-16 22:28:42.428  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 0 (0) 0 0
2023-01-16 22:28:42.435  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 3 (3) 0 0
2023-01-16 22:28:42.437  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 0 (0) 23 0
2023-01-16 22:28:42.464  7996-8065  EGL_emulation           tw.firemaples.onscreenocr_debug      D  eglMakeCurrent: 0xe3d875e0: ver 2 0 (tinfo 0xe232e6a0)
2023-01-16 22:28:42.537  2097-2196  GnssLocationProvider    system_process                       I  WakeLock acquired by sendMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@c5f36ee)
2023-01-16 22:28:42.537  2097-2124  GnssLocationProvider    system_process                       I  WakeLock released by handleMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@c5f36ee)
2023-01-16 22:28:42.616  7996-8065  EGL_emulation           tw.firemaples.onscreenocr_debug      D  eglMakeCurrent: 0xe3d875e0: ver 2 0 (tinfo 0xe232e6a0)
2023-01-16 22:28:42.617  7996-7996  chromium                tw.firemaples.onscreenocr_debug      I  [INFO:CONSOLE(0)] "Unrecognized Content-Security-Policy directive 'require-trusted-types-for'.
                                                                                                    ", source: https://www.google.com/search?tbm=isch&q=Photos (0)
2023-01-16 22:28:42.722  7996-8249  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 17 (17) 0 0
2023-01-16 22:28:42.727  7996-8249  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 1 (1) 0 0
2023-01-16 22:28:42.962  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      E  glUtilsParamSize: unknow param 0x000085b5
2023-01-16 22:28:42.962  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      E  glUtilsParamSize: unknow param 0x000085b5
2023-01-16 22:28:42.963  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 0 (0) 0 0
2023-01-16 22:28:42.964  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 3 (3) 0 0
2023-01-16 22:28:42.965  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 0 (0) 23 0
2023-01-16 22:28:42.989  7996-8065  OpenGLRenderer          tw.firemaples.onscreenocr_debug      I  Davey! duration=729ms; Flags=0, IntendedVsync=1408400448552, Vsync=1408583781878, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=1408596673000, AnimationStart=1408596715800, PerformTraversalsStart=1408598914300, DrawStart=1408756760100, SyncQueued=1408757034400, SyncStart=1408908127100, IssueDrawCommandsStart=1408908227700, SwapBuffers=1409272918600, FrameCompleted=1409280947900, DequeueBufferDuration=58000, QueueBufferDuration=292000, 
2023-01-16 22:28:42.992  7996-8065  EGL_emulation           tw.firemaples.onscreenocr_debug      D  eglMakeCurrent: 0xe3d875e0: ver 2 0 (tinfo 0xe232e6a0)
2023-01-16 22:28:43.049  7996-8065  EGL_emulation           tw.firemaples.onscreenocr_debug      D  eglMakeCurrent: 0xe3d875e0: ver 2 0 (tinfo 0xe232e6a0)
2023-01-16 22:28:43.175  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      E  glUtilsParamSize: unknow param 0x000085b5
2023-01-16 22:28:43.175  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      E  glUtilsParamSize: unknow param 0x000085b5
2023-01-16 22:28:43.175  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 0 (0) 0 0
2023-01-16 22:28:43.177  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 3 (3) 0 0
2023-01-16 22:28:43.201  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 0 (0) 23 0
2023-01-16 22:28:43.224  7996-8065  OpenGLRenderer          tw.firemaples.onscreenocr_debug      I  Davey! duration=885ms; Flags=0, IntendedVsync=1408598604812, Vsync=1408915271466, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=1408916771700, AnimationStart=1408916812800, PerformTraversalsStart=1408917766000, DrawStart=1409308745900, SyncQueued=1409309465600, SyncStart=1409341071800, IssueDrawCommandsStart=1409341219000, SwapBuffers=1409509130500, FrameCompleted=1409516129100, DequeueBufferDuration=179000, QueueBufferDuration=492000, 
2023-01-16 22:28:43.225  7996-8065  EGL_emulation           tw.firemaples.onscreenocr_debug      D  eglMakeCurrent: 0xe3d875e0: ver 2 0 (tinfo 0xe232e6a0)
2023-01-16 22:28:43.253  7996-7996  Choreographer           tw.firemaples.onscreenocr_debug      I  Skipped 37 frames!  The application may be doing too much work on its main thread.
2023-01-16 22:28:43.263  7996-8065  EGL_emulation           tw.firemaples.onscreenocr_debug      D  eglMakeCurrent: 0xe3d875e0: ver 2 0 (tinfo 0xe232e6a0)
2023-01-16 22:28:43.264  1611-1683  gralloc_ranchu          and...raphics.allocator@2.0-service  D  gralloc_alloc: Creating ashmem region of size 9551872
2023-01-16 22:28:43.371  7996-8249  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 17 (17) 0 0
2023-01-16 22:28:43.376  7996-8249  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 1 (1) 0 0
2023-01-16 22:28:43.407  7996-8065  OpenGLRenderer          tw.firemaples.onscreenocr_debug      I  Davey! duration=771ms; Flags=0, IntendedVsync=1408922838411, Vsync=1409539505053, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=1409544999800, AnimationStart=1409545051500, PerformTraversalsStart=1409548609400, DrawStart=1409548712200, SyncQueued=1409550367100, SyncStart=1409555408500, IssueDrawCommandsStart=1409578654600, SwapBuffers=1409689289400, FrameCompleted=1409699167800, DequeueBufferDuration=42000, QueueBufferDuration=183000, 
2023-01-16 22:28:43.468  2097-2196  GnssLocationProvider    system_process                       I  WakeLock acquired by sendMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@15b178f)
2023-01-16 22:28:43.469  2097-2124  GnssLocationProvider    system_process                       I  WakeLock released by handleMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@15b178f)
2023-01-16 22:28:43.511  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      E  glUtilsParamSize: unknow param 0x000085b5
2023-01-16 22:28:43.511  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      E  glUtilsParamSize: unknow param 0x000085b5
2023-01-16 22:28:43.511  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 0 (0) 0 0
2023-01-16 22:28:43.516  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 3 (3) 0 0
2023-01-16 22:28:43.521  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 0 (0) 0 0
2023-01-16 22:28:43.521  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 0 (0) 0 0
2023-01-16 22:28:43.606  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      E  glUtilsParamSize: unknow param 0x000085b5
2023-01-16 22:28:43.606  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      E  glUtilsParamSize: unknow param 0x000085b5
2023-01-16 22:28:43.606  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 0 (0) 0 0
2023-01-16 22:28:43.608  7996-8065  eglCodecCommon          tw.firemaples.onscreenocr_debug      D  setVertexArrayObject: set vao to 0 (0) 0 0
2023-01-16 22:28:43.613  1912-2288  SurfaceFlinger          surfaceflinger                       W  Attempting to destroy on removed layer: 1e8b6f6 tw.firemaples.onscreenocr_debug#0
2023-01-16 22:28:43.623  3008-3008  GoogleInputMethod       com...gle.android.inputmethod.latin  I  onFinishInput() : Dummy InputConnection bound
2023-01-16 22:28:43.624  3008-3008  GoogleInputMethod       com...gle.android.inputmethod.latin  I  onStartInput() : Dummy InputConnection bound
2023-01-16 22:28:43.664  7996-7996  chromium                tw.firemaples.onscreenocr_debug      I  [INFO:CONSOLE(375)] "%c%s", source: https://www.gstatic.com/_/mss/boq-search/_/js/k=boq-search.VisualFrontendUi.en_US.H-xIYGHMzzo.es5.O/am=XA4AAAAAeAwAAACAuQHCPwSC3HDDAQgMAAAgFWAAMBCQs-AJAOVxDCCADYCAh4WRkdbQE4HCAkgZixBAIEBcAQAAAAAA-w4ABgIAAAAAAAAAABDSDAAAAAAAAACEA10CAAAAACA/d=1/excm=_b,_r,_tp,searchview/ed=1/dg=0/wt=2/rs=AH7-fg4ifQ0g1EHy2YLIwsYai2ui0iMNqQ/m=_b,_tp,_r (375)
2023-01-16 22:28:43.670  7996-7996  chromium                tw.firemaples.onscreenocr_debug      I  [INFO:CONSOLE(375)] "%c%s", source: https://www.gstatic.com/_/mss/boq-search/_/js/k=boq-search.VisualFrontendUi.en_US.H-xIYGHMzzo.es5.O/am=XA4AAAAAeAwAAACAuQHCPwSC3HDDAQgMAAAgFWAAMBCQs-AJAOVxDCCADYCAh4WRkdbQE4HCAkgZixBAIEBcAQAAAAAA-w4ABgIAAAAAAAAAABDSDAAAAAAAAACEA10CAAAAACA/d=1/excm=_b,_r,_tp,searchview/ed=1/dg=0/wt=2/rs=AH7-fg4ifQ0g1EHy2YLIwsYai2ui0iMNqQ/m=_b,_tp,_r (375)
2023-01-16 22:28:43.691  2097-2124  memtrack                system_process                       E  Couldn't load memtrack module
2023-01-16 22:28:43.691  2097-2124  android.os.Debug        system_process                       W  failed to get memory consumption info: -1
2023-01-16 22:28:43.724  2097-2124  memtrack                system_process                       E  Couldn't load memtrack module
2023-01-16 22:28:43.724  2097-2124  android.os.Debug        system_process                       W  failed to get memory consumption info: -1
2023-01-16 22:28:44.303  3292-3292  MicroDetectionWorker    com....android.googlequicksearchbox  I  #startMicroDetector [speakerMode: 0]
2023-01-16 22:28:44.303  3292-3292  AudioController         com....android.googlequicksearchbox  I  Using mInputStreamFactoryBuilder
2023-01-16 22:28:44.303  3292-3292  AudioController         com....android.googlequicksearchbox  I  Created new AudioSource
2023-01-16 22:28:44.305  3292-3292  MicroDetectionWorker    com....android.googlequicksearchbox  I  onReady

**Comment by firemaples** [comment]
Can not find any error in your log
Did you touch the background of the WebView? I mean the area outside of the WebView, that will close the WebView.
I think I should remove this action first then test more times.

**Comment by uomar8** [comment]
> Can not find any error in your log Did you touch the background of the WebView? I mean the area outside the WebView, that will close the WebView. I think I should remove this behavior first and then test it more times.

I think you're absolutely right 😆💔💔 I think I clicked between buttons now it makes sense

I think it's better to remove that area or it shouldn't work near buttons but I'm more with remove it

**Comment by firemaples** [comment]
I removed it in #234, since the WebView page can be closed by pressing the back button and the closing button, removing the behavior can be more reasonable. 😁

**Comment by uomar8** [comment]
> I removed it in #234, since the WebView page can be closed by pressing the back button and the closing button, removing the behavior can be more reasonable. 😁

Now it's perfect 👍

**Comment by firemaples** [comment]
The v3.1.8 version has been sent to the Beta channel and waiting for approval by PlayStore.
If there's no fatal crash tomorrow, I'll release it in the Production channel progressively.

**Pull request merged**
