### PR TITLE
Force some layout display in LTR

### PR DESCRIPTION
**Pull request by uomar8**
layouts does not support RTL (languages)

that's why I decided to force LTR on them

Screenshot_20230125_003003
Screenshot_20230125_003019
Screenshot_20230125_003239

### CODE REVIEW

**Comment by firemaples** [comment]
Instead of adding `android:layoutDirection="ltr"` to every view file, how about changing the `android:supportsRtl="true"` to `false` on the `<application/>` tag in the `AndroidManifest.xml` file?

**Comment by uomar8** [comment]
> Thanks for the testing of RTL mode.
> 
> Instead of adding `android:layoutDirection="ltr"` to every view file, how about changing the `android:supportsRtl="true"` to `false` on the `<application/>` tag in the `AndroidManifest.xml` file?

This could work too

But other layouts support RTL and they looks great 😌 I prefer to fix 4 layouts instead of turning them off

But for now
 `android:supportsRtl="true"`
Or
`android:layoutDirection="ltr"` on these 4

Are good (temporary) solution

**Comment by firemaples** [comment]
> > Thanks for the testing of RTL mode.
> > Instead of adding `android:layoutDirection="ltr"` to every view file, how about changing the `android:supportsRtl="true"` to `false` on the `<application/>` tag in the `AndroidManifest.xml` file?
> 
> This could work too
> 
> But other layouts support RTL and they looks great 😌 I prefer to fix 4 layouts instead of turning them off
> 
> But for now `android:supportsRtl="true"` Or `android:layoutDirection="ltr"` on these 4
> 
> Are good (temporary) solution

Get it, thank you!

**Comment by firemaples** [comment]
Looks great, thank you for the contribution! 🎉

**Pull request merged**
