### PR TITLE
vertical main bar setting

### PR DESCRIPTION
**Pull request by uomar8**
I tried to make a switch between vertical and horizontal and it works

what need to be fixed

vertical mode looks ugly
didn't add string yet
there's no warning that you have to click hide and show from the notification so it can change :) if this could be done by code it would be better than warning

### CODE REVIEW

**Comment by firemaples** [comment]
Okay, let me check it.

**Comment by firemaples** [comment]
I'm still thinking about the vertical UI. 😅

**Comment by uomar8** [comment]
> 

Could it be done on different layout1(horizontal) layout2 (vertical)

Something like this? 
https://stackoverflow.com/questions/26574589/using-multiple-layouts-in-single-activity

**Comment by firemaples** [comment]
Yes, it can be two different layouts

**Pull request closed without merging**
