### PR TITLE
Move requestBattery to settings page

### PR DESCRIPTION
**Pull request by uomar8**
hide requestBattery at the beginning  so it won't show two buttons

### CODE REVIEW

**Comment by firemaples** [comment]
> hide requestBattery at the beginning so it won't show two buttons

Agree, displaying two request buttons on the same screen is weird.
But when will it be displayed? Or move it to the setting page?

**Comment by uomar8** [comment]
> > hide requestBattery at the beginning so it won't show two buttons
> 
> Agree, displaying two request buttons on the same screen is weird. But when will it be displayed? Or move it to the setting page?

(this only happens on new install)

once permission_float_window_fragment.xml loaded it display two button but only one work but once you click bt_requestPermission and permission_capture_screen_fragment.xml loaded here you can click both buttons and both works

and you're right show both buttons isn't ideal for new users it would be better to show only one and once it done it should show the other one

**Comment by firemaples** [comment]
Okay, let's move it to the setting page.

**Comment by uomar8** [comment]
> Okay, let's move it to the setting page.

I was busy today my apologies I couldn't do it

**Comment by firemaples** [comment]
@uomar8 Don't apologize, and don't be hurry. 
Except you want this feature on PlayStore immediately.
I'm also busy in these days, and will continue being busy for 2 or 3 months 😩

**Comment by uomar8** [comment]
> @uomar8 Don't apologize, and don't be hurry. it's not your responsibility, except you want this feature on PlayStore immediately. I'm also busy in these days, and will continue being busy for 2 or 3 months 😩

Thank you 😆💔 to be honest I really want it in 2 3 days at maximum, also I saw how hard it's so I understand how it takes time and so much experience 

I know this is not related to the pull request but thank you so much for your great work and your great app and your great personality I really felt like a partner and I appreciate thank you so much again

**Comment by firemaples** [comment]
> > @uomar8 Don't apologize, and don't be hurry. it's not your responsibility, except you want this feature on PlayStore immediately. I'm also busy in these days, and will continue being busy for 2 or 3 months 😩
> 
> Thank you 😆💔 to be honest I really want it in 2 3 days at maximum, also I saw how hard it's so I understand how it takes time and so much experience
> 
> I know this is not related to the pull request but thank you so much for your great work and your great app and your great personality I really felt like a partner and I appreciate thank you so much again

Thank you, too!
I'm also very excited about your contributions, and you're the first and only contributor to this project.😆
That makes me feel I have a partner and I'm really on work on an open-sourced project.😁
I'll try to finish this and the single work selector these days.😀
And maybe you can try to suggest the priority of pull requests and issues so I can know about the ordering you want.

**Comment by firemaples** [comment]
@uomar8, I will release the v3.1.8 version with this feature tomorrow if there are no other concerns. 🎉

**Pull request merged**
