### PR TITLE
select one word mode just like Quick Translator

### PR DESCRIPTION
**Pull request by uomar8**
I tried to make one word mode same as  Quick Translator

I think the code work fine but could you please improve it

also sorry for the work

### CODE REVIEW

**Comment by uomar8** [comment]
This one is updated in [#224](https://github.com/firemaples/EverTranslator/pull/224) to do open Google images

**Comment by uomar8** [comment]
just test it out works great 
the only thing i hope to fix is (Hyphenated Compound Words) for example:

 free-for-all or know-how 

it should select the whole word instead it select part of it, I tried to fix it but I don't know how

**Comment by firemaples** [comment]
> just test it out works great the only thing i hope to fix is (Hyphenated Compound Words) for example:
> 
> free-for-all or know-how
> 
> it should select the whole word instead it select part of it, I tried to fix it but I don't know how

Please check this version, I'm not sure whether I've handled most of the situations or not.

**Comment by uomar8** [comment]
> > just test it out works great the only thing i hope to fix is (Hyphenated Compound Words) for example:
> > free-for-all or know-how
> > it should select the whole word instead it select part of it, I tried to fix it but I don't know how
> 
> Please check this version, I'm not sure whether I've handled most of the situations or not.

Perfect amazing work as always 👍👍👍

**Pull request closed without merging**
