### PR TITLE
update libraries + fix some build bugs

### PR DESCRIPTION
**Pull request by uomar8**
still theres warning in  Task :main:compileDevDebugKotlin

### CODE REVIEW

**Comment by firemaples** [comment]
Thanks for updating dependencies, have you tried this app on Android 13?

**Comment by uomar8** [comment]
> Thanks for updating the dependencies. I have a question, have you tried this app on Android 13? 🤔

No I only tried on my phone, if you could check that would be great and if there's problem we could work on that

**Comment by uomar8** [comment]
> Thanks for updating the dependencies. I have a question, have you tried this app on Android 13? thinking

Just tested on Android studio emulator
Pixel 5 API 33

Most of the time it won't take screenshots correctly it will show black screen
IMG_20230514_100213

Only 2 times out of 14 worked and took screenshot
IMG_20230514_104413

Logcat didn't show any error or any warning 🤔

**Comment by uomar8** [comment]
Android 14 works great

**Comment by firemaples** [comment]
Sorry for not replying for a long time 🙇‍♂️. Thank you for the tests.
My phone is still Android 12, let me also test it on an emulator and check what happened.

**Comment by uomar8** [comment]
> Sorry for not replying for a long time bowing_man. Thank you for the tests. My phone is still Android 12, let me also test it on an emulator and check what happened.

That's okay take your time 👍

**Comment by firemaples** [comment]
Sorry for reply so late, I'll test it a day

> > Thanks for updating the dependencies. I have a question, have you tried this app on Android 13? thinking
> 
> Just tested on Android studio emulator Pixel 5 API 33
> 
> Most of the time it won't take screenshots correctly it will show black screen IMG_20230514_100213
> 
> Only 2 times out of 14 worked and took screenshot IMG_20230514_104413
> 
> Logcat didn't show any error or any warning 🤔
> 
> Edit: Same with version 3.1.15

It also happens sometimes on my side, but I don't have an Android 13 real device right now.
Anyway, I'll push this version to beta channel first to check it works well or not.
Thank you for your help 🙇‍♂️

**Pull request merged**
